
export const RAW_CSV_DATA = `Nama  / Nama Panggilan,Usia,Email atau No. Whatsapp,"Saya pernah atau sering menonton video youtube tentang keuangan syariah (larangan riba, cara mengelola hutang, cari modal ke bank syariah, dll)",Bentuk konfirmasi,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28,Q29,Q30
Pilar,18,83822813341,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Irpan Mulyadi,25,87733940992,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Setuju,Netral,Setuju
Kidam,21,83807464449,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju
Akbar,21,83180112238,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Rizky Nur M,20,89520208066,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju
Dinda Octavia,21,85624673967,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Netral,Setuju,Netral,Setuju,Netral,Sangat Setuju
rima,27,85724859002,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Netral,Netral,Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Netral,Netral,Setuju,Setuju,Netral,Setuju,Setuju
Sandi Suryono ,25,82127380316,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
mey,20,89656530252,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Netral,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju
Resti,20,85724070025,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju
Sopia ,20,81224344604,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Setuju,Netral,Netral,Netral,Setuju,Setuju,Setuju,Setuju
Cindy,20 tahun,85797011233,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju
Yulinda Akhiriyanti/ linda,20,82119077616,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Abdulloh ,23,abdullohadzmatkhan@gmail.com,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral,Netral
Agung Sucianto ,22,81367781762,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju
Ujang taopik,20,82320343038,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Tidak Setuju,Tidak Setuju,Tidak Setuju,Setuju,Sangat Setuju,Netral,Netral,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Tidak Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Cucu Nurdiansah ,21,cucunurdiansah61@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Netral,Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
evii,20,82329700053,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Zahra ,21,89676287533,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Tidak Setuju,Sangat Setuju,Sangat Tidak Setuju,Tidak Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Tia Puspita Sari,21,81220504253,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Netral,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Salman,17 tahun,85786782278,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Netral,Netral,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Netral,Netral,Sangat Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Elisaamelia ,17tahun,82321318828,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Netral,Netral,Netral,Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Netral,Setuju,Setuju,Setuju,Setuju
Diaz Vikri Wahyudi/ Diaz ,17,karbitdiaz@gmail.com,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju
Jesika,15thn,83832104266,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Netral,Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Riris,17,88218676602,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju
salwa n.s ,17 thn,83844324875,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Netral,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Sangat Setuju
ririnsriregina ,15 tahun,882000350856,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Netral,Netral,Sangat tidak setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Setuju
Handz,18,0851 7532 8226 ,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
jejen,17 tahun,+62 88223621739,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju
Aidha Indriyani,16,81312475731,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Netral,Sangat Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Netral,Netral,Setuju,Netral,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Netral,Netral,Setuju,Netral,Sangat Setuju
Datuk,17,sopianiwan138@gmail.com,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat tidak setuju,Sangat tidak setuju,Sangat tidak setuju,Sangat tidak setuju,Setuju,Netral,Tidak Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat tidak setuju,Setuju,Setuju,Setuju,Sangat tidak setuju
Iki,18,0831 5577 3100,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Netral,Netral,Setuju,Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
M. REYHAN FADILLAH ,18,895620061287,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju
latief,17,85794569698,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Netral,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat tidak setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju
Komala S.N.A,17 tahun,85703868344,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Sangat Setuju
Aini,22,83837329967,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Netral,Setuju,Netral,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju
Zul,19,81286406547,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Netral,Setuju,Setuju,Setuju,Setuju
sasa,16,+62 822-2769-2875,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Netral,Netral,Setuju,Netral,Setuju,Netral,Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Netral,Setuju,Netral,Netral,Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Netral,Netral,Setuju,Setuju,Netral
Asep Rif'at Mushowwir ,16 Tahun,85624367157,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Netral,Netral,Sangat Setuju,Netral,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju
Aurel,23,82284465272,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
David,23 tahun,89655838093,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Netral,Netral,Netral,Setuju,Netral,Setuju,Netral,Tidak Setuju,Netral,Netral,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
caca salsabila,17,83113148890,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Netral,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
berliana Oktavia ,17,6283169351358,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju
Aldi,17,89520364733,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Netral,Setuju,Setuju,Netral,Sangat Setuju
Herul,18,85624915912,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju
Asep Rif'at Mushowwir ,16 tahun,85624367157,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju
Acil,23,sejarahmedia26@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Netral,Setuju,Netral,Setuju,Setuju,Setuju,Netral,Setuju,Netral,Setuju,Netral,Setuju,Setuju,Setuju,Netral,Netral,Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Tidak Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju
nurul,16,82119729663,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Netral,Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Om,26,895635017818,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Imel,23,83817730589,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Arlinda,37,82120004630,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Netral,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Ramdani Permana Abduh,17,85295713774,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Nanda,17,82125204445,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Netral,Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Netral,Sangat Setuju,Netral,Sangat Setuju
Yesi Ramadani,22,83865782466,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Netral,Tidak Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Muhammad hasan setiawan ,16,83865477763,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Tidak Setuju,Setuju,Netral,Sangat Setuju,Setuju,Setuju
Senja gumelar,17,83108056409,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju
Muhamad Ridwan,16,81572579484,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Setuju
Alam,22,88222830038,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Setuju,Tidak Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Tidak Setuju,Setuju,Tidak Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Syahrul,16,8818250141,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Netral,Sangat Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Tidak Setuju,Tidak Setuju,Netral,Netral,Sangat Setuju
Cecep Tarkiman ,17 tahun,82331742069,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Netral,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju
Nurul Anggraeni,19,81563808537,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju
Aliman Fauzi,25,85720686746,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Bela sapitri ,21,85183510517,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Setuju,Setuju
Doni Romadon ,22,dzoniromadhon46@gmail.com,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Widya,21,wiwinwidyaningsih71@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Netral,Setuju,Netral,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Fai,21,89618915452,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Netral,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Netral
Hilmi,21,82320778710,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju
Agus Triswanto,25,85723929856,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju
Fadel ,25,85161754417,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
FRANSISKA,19,89517828330,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Netral,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
risqi,18,82119564407,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Tidak Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
M.Syahlaa.R.H,18 tahun,89508706116,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju
Nuy,21,"082256405231 (kalau dapet, spay aja ya a hehe)",Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
nidaaa,20,pakenya gopay a wkwkwk 08822032038,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Della ,20,dellabil9f7@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Deva,21,89655703839,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Netral,Sangat Setuju,Netral,Sangat Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju
Ayi Lesmana ,23,85846248543,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Yonkage ,22,8112075457,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju
Azfa Nabila,20th,87727267785,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Netral,Tidak Setuju,Setuju,Setuju,Sangat Setuju,Setuju,
Meira,24,81222648214,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Dea,20,deadeslianti2004@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Ica,21,88220701021,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Setuju
silma,22,81384042542,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Netral,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
𝚠𝚊𝚛𝚝𝚒𝚔𝚊𝚗𝚞𝚛𝚜𝚎𝚕𝚊,𝟷𝟿,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Netral,Netral,Setuju,Tidak Setuju,Setuju,Tidak Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,,,,,,,,,,,,,
Levi,21,Levianyrudianti@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju
Vani Angreani/Vani,21 Tahun,angraenivani@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju
Raisa,21 tahun,81220120532,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Setuju,Netral,Setuju,Netral,Setuju
Safina Nur Rahmah,22,87852774630,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju
Yusril,22,82245494050,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Netral,Netral,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Andini,21,81323087634,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat tidak setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat tidak setuju,Sangat tidak setuju,Sangat tidak setuju,Sangat tidak setuju,Sangat tidak setuju
Fira,22 tahun,85315825425,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Setuju,Netral,Netral,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Tidak Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
cita,23,83817306165,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Randi,24,83186192786,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Tidak Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Musa angkasa putra,21,895391277797,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat tidak setuju,Sangat tidak setuju,Sangat tidak setuju,Sangat tidak setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju
Gibran,21,88809471662,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Netral,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Hilma Khoufy ,22 Tahun,85794735283,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Allyssa,26,85703721024,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Tidak Setuju,Netral,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju
aini,22,83837329967,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju
Dila,21,81993003664,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju
Lastri,27 tahun,89657370944,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Netral,Netral,Netral,Netral,Netral,Setuju,Sangat Setuju,Sangat Setuju,Netral,Netral,Netral,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju
Barkah Nur Muhamad,22,85150690460,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju
Thufail,25,82131204603,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Tidak Setuju,Netral,Sangat Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Netral
Abdul ,23,895330031349,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Tidak Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju
Fatah,20,85861179604,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Lisna,21,83869449043,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju
Rina anjani,25,8534127547678,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju
sofia,25,8164347377977,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju
Novan arthanto,27,817627347558,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Sangat Setuju
Theresia,24,817657257589,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju
Theo galexio,27,8524217357658,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju
Nisa arunika,27,82462754767,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Netral,Setuju,Netral,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Setuju,Setuju,Sangat Setuju
Namira,25,81462754787,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Netral,Netral,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Setuju
Dewi Dania Astuti ,23,dewiastutiiiiii34@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju
Jajang Suherman ,27,jajangsuher911@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju
Angga Maulana ,25,anggamauln00@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju
Indah Wulandari ,22,indahwww997@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju
Rayyan Syauqi ,24,syauqir163@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju
Dewa Saputra ,26,dewas7845@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju
Annisa Aulia ,22,nisaulannisa325@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju
Anggin lupita ,23,angginlupita84@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju
Latifah indira,23,85542486785,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju
Mei Afidah,25,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju
Nita,26,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Setuju
Khoirul Anam ,25,85794435257,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju
Rayhan saputra,24,8546272445748,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju
Eta Maharani,25,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju
Ara Wulandari,26,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju
Endri saliman,26,8242475472745,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju
Miftahul Jannah,25,https://forms.gle/i6WuLAJrt5DFpi6n6,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Setuju
Anggoro nur Permana ,24,89776857982,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju
Fauzan Wibisono ,26 Tahun,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju
Reski adi putra,20,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Netral,Tidak Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju
Riri Sabrina ,24 Tahun,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju
Gilang Ardeanta,20,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Netral,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Setuju
Khoirunnisa ,23,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Netral
Tomi Wijaya,23,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Netral,Netral,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Netral,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju
Adalia Niskala,23,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju
Valdi,27,87728930200,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Andre Mahendra,26,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju
Bisma,20,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Aruni Nawasena,21,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Netral,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Setuju,Setuju
Diah rahmawati,24,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju
Andini Khansa,23,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Setuju,Netral,Netral,Sangat Setuju,Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Netral,Netral,Sangat Setuju,Netral,Netral,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju
Ahmad heryawan,20,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju
Nada Fauziah  ,27 Tahun,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju
Andhika Fajrin,26,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Netral,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju
Bima Saputra ,27 Tahun,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju
Alkananta Sukma,27,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Netral,Netral,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Setuju
Damar Aji,25,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju
Syakira Amelia Putri ,22 Tahun,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju
Tasha Aalisha,23,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Netral,Netral,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju
Muhammad Cahyo,25,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju
Putu hamidah,23,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju
Dian Saputra,25,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju
Cakra Abhista,27,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Setuju,Netral,Sangat Setuju,Netral,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Netral,Netral,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju
Denis,23,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju
Binar via Muhajadah,23,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Netral,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju
Kevin Bimantara,25,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Netral,Sangat Setuju,Setuju,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Netral,Netral,Sangat Setuju,Setuju,Netral,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Netral,Sangat Setuju,Sangat Setuju,Netral
Dafa,23 Tahun,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju
Lintang wicaksana,25,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Netral,Netral,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju
Zahra,20 Tahun,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju
Lutfi Wildan,26,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju
Khoirun Najib,25,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju
Andre,25 Tahun,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju
Amira ,21 Tahun,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju
Reyhan Pranata ,23 Tahun,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju
Jemmy,21,81909394644,Saya belum pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Netral,Setuju,Sangat tidak setuju,Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Tidak Setuju,Sangat Setuju,Setuju,Setuju,Netral,Setuju,Netral,Setuju,Netral,Setuju
RZ,19,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju
Arya Danuwiar ,25,,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Setuju
Anton ,20,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju
Latifa Aulia ,22,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju
Latifa Aulia ,19,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Netral,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Setuju
Reikita Civani ,24,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju
Jonathan ,18,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Tidak Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Netral,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Setuju
Putri Jamalia ,17,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju
Mustofa Bisri ,27,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Sangat Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju
Viey,25,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Netral,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju
Fitri Kurnia ,23,,Saya sering menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Netral,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju
Ismie I. Arfah,22,895416188269,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Netral,Setuju,Setuju,Setuju
Fatia Nursyifa,22 tahun,fathianursyifa8@gmail.com,Saya pernah menontonnya,Saya mengkonfirmasi bahwa data yang saya berikan diisi dengan jujur dan berniat membantu penelitian.,Setuju,Sangat Setuju,Netral,Netral,Netral,Netral,Sangat Setuju,Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju,Sangat Setuju`;
